pref(
  'vivipos.fec.settings.controlpanels.config.gosky_member_settings.icon',
  'chrome://gosky_member/skin/images/gosky_member_Logo.png'
)
pref(
  'vivipos.fec.settings.controlpanels.config.gosky_member_settings.label',
  'chrome://gosky_member/locale/messages.properties'
)
pref(
  'vivipos.fec.settings.controlpanels.config.gosky_member_settings.path',
  'chrome://gosky_member/content/settings.xul'
)
pref(
  'vivipos.fec.settings.controlpanels.config.gosky_member_settings.roles',
  'acl_gosky_member_settings'
)
